/* ============================================================
   データ: アイテム（素材・完成品・消費アイテム・アーティファクト）
   ============================================================ */

/* ── アイテム日本語名 ── */
const ITEM_JA = {
  'B.F. Sword': 'B.F.ソード', 'Recurve Bow': 'リカーブボウ', 'Needlessly Large Rod': 'ムダニデカイロッド',
  'Tear of the Goddess': '女神の涙', 'Chain Vest': 'チェインベスト', 'Negatron Cloak': 'ネガトロンクローク',
  "Giant's Belt": 'ジャイアントベルト', 'Sparring Gloves': 'スパーリンググローブ', 'deathblade': 'デスブレード',
  'Giant Slayer': 'ジャイアントスレイヤー', 'Hextech Gunblade': 'ヘクステックガンブレード', 'spearofshojin': 'ショウジンの矛',
  'guardianangel': 'ナイトエッジ', 'Bloodthirster': 'ブラッドサースター', 'steraksgage': 'ステラックの篭手',
  'Infinity Edge': 'インフィニティエッジ', 'rapidfirecannon': 'レッドバフ', "Guinsoo's Rageblade": 'グインソー レイジブレード',
  'statikkshiv': 'ヴォイドスタッフ', "Titan's Resolve": '巨人の誓い', 'runaanshurricane': 'クラーケンの怒り',
  "Nashor's Tooth": 'ナッシャー トゥース', 'Last Whisper': 'ラストウィスパー', "Rabadon's Deathcap": 'ラバドンデスキャップ',
  "Archangel's Staff": 'アークエンジェルスタッフ', 'Crownguard': 'クラウンガード', 'Ionic Spark': 'アイオニックスパーク',
  'Morellonomicon': 'モレロノミコン', 'Jeweled Gauntlet': 'ジュエル ガントレット', 'Blue Buff': 'ブルーバフ',
  'frozenheart': 'プロテクターの誓い', 'Adaptive Helm': 'アダプティブヘルム', 'Redemption': 'スピリット ビサージュ',
  'unstableconcoction': 'ハンド オブ ジャスティス', 'Bramble Vest': 'ブランブルベスト', 'Gargoyle Stoneplate': 'ガーゴイルストーンプレート',
  'redbuff': 'サンファイアケープ', 'nightharvester': '揺るがぬ心', "Dragon's Claw": 'ドラゴン クロウ',
  'spectralgauntlet': 'イーブンシュラウド', 'Quicksilver': 'クイックシルバー', "Warmog's Armor": 'ワーモグ アーマー',
  'powergauntlet': 'ストライカー フレイル', "Thief's Gloves": '盗賊のグローブ',
  'Tiny Champion Duplicator': '小さなチャンピオン複製機',
  'Lesser Champion Duplicator': '小型チャンピオン複製機',
  'Champion Duplicator': 'チャンピオン複製機',
  'Reforger': '再合成装置',
  'Magnetic Remover': '磁力式除去装置',
  'Spatula': '黄金のへら',
  'Frying Pan': 'フライパン',
  'Dark Star Emblem': 'ダークスターの紋章',
  'pulsefire Emblem': 'タイムブレイカーの紋章',
  'Stargazer Emblem': '星の観測者の紋章',
  'Space Groove Emblem': 'スペースグルーヴの紋章',
  'astronaut Emblem': 'ミィプルの紋章',
  'favored Emblem': 'アービターの紋章',
  'Primordian Emblem': 'プリモーディアンの紋章',
  'drx Emblem': 'N.O.V.A.の紋章',
  'meleetrait Emblem': '略奪者の紋章',
  'astrait Emblem': 'チャレンジャーの紋章',
  'flextrait Emblem': 'ボイジャーの紋章',
  'summontrait Emblem': '導き手の紋章',
  'resisttank Emblem': 'バスティオンの紋章',
  'shieldtank Emblem': 'ヴァンガードの紋章',
  'hptank Emblem': 'ブローラーの紋章',
  'assassintrait Emblem': 'ローグの紋章',
  'animasquad Emblem': 'アニマの紋章',
  'Psyops Emblem': 'サイオニックの紋章',
  'rangedtrait Emblem': 'スナイパーの紋章',
  "forceofnature": 'タクティシャンの王冠',
  "Ahri's Aura": 'アーリのオーラ',
  "Evelynn's Intuition": 'イブリンの直感',
  "Trinity Force": 'インフィニティ フォース',
  "Varus's Tenacity": 'ヴァルスの執念',
  "Wit's End": 'ウィッツ エンド',
  "Void Gauntlet": 'ヴォイド ガントレット',
  "Ekko's Patience": 'エコーの忍耐',
  "Gambler's Blade": 'ギャンブラーの剣',
  "The Collector": 'ゴールド コレクター',
  "Seeker's Armguard": 'シーカー アームガード',
  "Silvermere Dawn": 'シルバーミアの夜明け',
  "Statikk Shiv Artifact": 'スタティック シヴ',
  "Sniper's Focus": 'スナイパー フォーカス',
  "Thresh's Lantern": 'スレッシュのランタン',
  "Zhonya's Paradox": 'ゾーニャの砂時計',
  "Soraka's Miracle": 'ソラカの奇跡',
  "Titanic Hydra": 'タイタン ハイドラ',
  "Death's Defiance": 'デス ディファイアンス',
  "Dawncore": 'ドーンコア',
  "Hullcrusher": 'ハルクラッシャー',
  "Fishbones": 'フィッシュボーン',
  "Flickerblade": 'フリッカーブレード',
  "Prowler's Claw": 'プローラー クロウ',
  "Mittens": 'ミトン',
  "Mogul's Mail": 'モーグル メイル',
  "Yasuo's Bladework": 'ヤスオのブレードワーク',
  "Lightshield Crest": 'ライトシールドのクレスト',
  "Rapid Firecannon Artifact": 'ラピッド ファイアキャノン',
  "Lich Bane": 'リッチ ベイン',
  "Luden's Tempest": 'ルーデン テンペスト',
  "Unending Despair": '不屈',
  "Everlasting Pact": '不滅の協定',
  "Dusk's Blessing": '夕闇の加護',
  "Dawn's Blessing": '夜明けの加護',
  "Hat Juice": '帽子ジュース',
  "Blighting Jewel": '枯死の宝石',
  "Hellfire Hatchet": '獄炎のハチェット',
  "Talisman of Ascension": '超越のタリスマン',
};

/* ── 素材アイテム ── */
const ITEMS=[
  {id:'bf', name:'B.F. Sword', icon:'⚔️', type:'comp', imgId: 1}, 
  {id:'bow', name:'Recurve Bow', icon:'🏹', type:'comp', imgId: 2},
  {id:'rod', name:'Needlessly Large Rod', icon:'🔮', type:'comp', imgId: 3}, 
  {id:'tear', name:'Tear of the Goddess', icon:'💧', type:'comp', imgId: 4},
  {id:'chain', name:'Chain Vest', icon:'🛡️', type:'comp', imgId: 5}, 
  {id:'cloak', name:'Negatron Cloak', icon:'🧥', type:'comp', imgId: 6},
  {id:'belt', name:"Giant's Belt", icon:'💖', type:'comp', imgId: 7}, 
  {id:'glove', name:'Sparring Gloves', icon:'🥊', type:'comp', imgId: 9},
  {id:'spatula', name:'Spatula', icon:'🍳', type:'comp', imgId: 8},
  {id:'pan', name:'Frying Pan', icon:'🥘', type:'comp', imgId: 10}
];

/* ── サイオニック専用アイテム ── */
const PSIONIC_ITEMS = [
  { name: 'tft17_item_psyops_targetlockmod', jaName: 'ターゲットロック スコープ' },
  { name: 'tft17_item_psyops_sympatheticimplantmod', jaName: '共感インプラント' },
  { name: 'tft17_item_psyops_dronemod', jaName: 'ドローン アップリンク' },
  { name: 'tft17_item_psyops_chemicalcapacitormod', jaName: 'マルウェア マトリックス' },
  { name: 'tft17_item_psyops_grenademod', jaName: 'バイオ物質保存装置' }
];

/* ── 完成アイテムのレシピ ── */
const ITEM_RECIPES = {
  'bf_bf':{id:'deathblade', name:'deathblade', icon:'🗡️', imgId: 11}, 
  'bf_bow':{id:'giantslayer', name:'Giant Slayer', icon:'🪚', imgId: 12},
  'bf_rod':{id:'gunblade', name:'Hextech Gunblade', icon:'🔫', imgId: 13}, 
  'bf_tear':{id:'shojin', name:'spearofshojin', icon:'🔱', imgId: 14},
  'bf_chain':{id:'edgeofnight', name:'guardianangel', icon:'🌑', imgId: 15}, 
  'bf_cloak':{id:'bloodthirster', name:'Bloodthirster', icon:'🧛', imgId: 16},
  'bf_belt':{id:'steraksgage', name:"steraksgage", icon:'💪', imgId: 17}, 
  'bf_glove':{id:'infinityedge', name:'Infinity Edge', icon:'✨', imgId: 19},
  'bow_bow':{id:'rapidfirecannon', name:'rapidfirecannon', icon:'🔥', imgId: 22}, 
  'bow_rod':{id:'guinsoo', name:"Guinsoo's Rageblade", icon:'☄️', imgId: 23},
  'bow_tear':{id:'statikk', name:'statikkshiv', icon:'⚡', imgId: 24}, 
  'bow_chain':{id:'titans', name:"Titan's Resolve", icon:'🗿', imgId: 25},
  'bow_cloak':{id:'runaan', name:"runaanshurricane", icon:'🌪️', imgId: 26}, 
  'bow_belt':{id:'nashor', name:"leviathan", icon:'🦷', imgId: 27},
  'bow_glove':{id:'lastwhisper', name:'Last Whisper', icon:'🏹', imgId: 29},
  'rod_rod':{id:'rabadon', name:"Rabadon's Deathcap", icon:'🎩', imgId: 33}, 
  'rod_tear':{id:'archangel', name:"Archangel's Staff", icon:'👼', imgId: 34},
  'rod_chain':{id:'crownguard', name:'Crownguard', icon:'👑', imgId: 35}, 
  'rod_cloak':{id:'ionic', name:'Ionic Spark', icon:'🌩️', imgId: 36},
  'rod_belt':{id:'morello', name:'Morellonomicon', icon:'📜', imgId: 37}, 
  'rod_glove':{id:'jeweled', name:'Jeweled Gauntlet', icon:'💎', imgId: 39},
  'tear_tear':{id:'bluebuff', name:'Blue Buff', icon:'🟦', imgId: 44}, 
  'tear_chain':{id:'vow', name:"frozenheart", icon:'🤝', imgId: 45},
  'tear_cloak':{id:'adaptive', name:'Adaptive Helm', icon:'🪖', imgId: 46}, 
  'tear_belt':{id:'redemption', name:'Redemption', icon:'😇', imgId: 47},
  'tear_glove':{id:'hoj', name:'unstableconcoction', icon:'⚖️', imgId: 49},
  'chain_chain':{id:'bramble', name:'Bramble Vest', icon:'🌵', imgId: 55}, 
  'chain_cloak':{id:'gargoyle', name:'Gargoyle Stoneplate', icon:'🗿', imgId: 56},
  'chain_belt':{id:'sunfire', name:'redbuff', icon:'☀️', imgId: 57}, 
  'chain_glove':{id:'steadfast', name:'nightharvester', icon:'❤️', imgId: 59},
  'cloak_cloak':{id:'dragon', name:"Dragon's Claw", icon:'🐉', imgId: 66}, 
  'cloak_belt':{id:'evenshroud', name:'spectralgauntlet', icon:'🦇', imgId: 67},
  'cloak_glove':{id:'quicksilver', name:'Quicksilver', icon:'🧣', imgId: 69}, 
  'belt_belt':{id:'warmog', name:"Warmog's Armor", icon:'🌿', imgId: 77}, 
  'belt_glove':{id:'guardbreaker', name:'powergauntlet', icon:'🔨', imgId: 79}, 
  'glove_glove':{id:'thiefs', name:"Thief's Gloves", icon:'🧤', imgId: 99},
  'spatula_bf':{id:'emblem_darkstar', name:'Dark Star Emblem', icon:'🛡️', imgId: 81, grantedTrait: 'Dark Star'}, 
  'spatula_bow':{id:'emblem_timebreaker', name:'pulsefire Emblem', icon:'🏹', imgId: 82, grantedTrait: 'Timebreaker'},
  'spatula_rod':{id:'emblem_stargazer', name:'Stargazer Emblem', icon:'🔮', imgId: 83, grantedTrait: 'Stargazer'}, 
  'spatula_tear':{id:'emblem_spacegroove', name:'SpaceGroove Emblem', icon:'💧', imgId: 84, grantedTrait: 'Space Groove'},
  'spatula_chain':{id:'emblem_meeple', name:'astronaut Emblem', icon:'🛡️', imgId: 85, grantedTrait: 'Meeple'}, 
  'spatula_cloak':{id:'emblem_arbiter', name:'favored Emblem', icon:'🧥', imgId: 86, grantedTrait: 'Arbiter'},
  'spatula_belt':{id:'emblem_primordian', name:'Primordian Emblem', icon:'💖', imgId: 87, grantedTrait: 'Primordian'}, 
  'spatula_glove':{id:'emblem_nova', name:'drx Emblem', icon:'🥊', imgId: 89, grantedTrait: 'N.O.V.A.'},
  'spatula_spatula':{id:'tacticians_crown', name:"forceofnature", icon:'👑', imgId: 88, teamSizeBonus: 1},
  'pan_bf':{id:'emblem_marauder', name:'meleetrait Emblem', icon:'🛡️', imgId: 91, grantedTrait: 'Marauder'},
  'pan_bow':{id:'emblem_challenger', name:'astrait Emblem', icon:'🏹', imgId: 92, grantedTrait: 'Challenger'},
  'pan_rod':{id:'emblem_voyager', name:'flextrait Emblem', icon:'🔮', imgId: 93, grantedTrait: 'Voyager'},
  'pan_tear':{id:'emblem_shepherd', name:'summontrait Emblem', icon:'💧', imgId: 94, grantedTrait: 'Shepherd'},
  'pan_chain':{id:'emblem_bastion', name:'resisttank Emblem', icon:'🛡️', imgId: 95, grantedTrait: 'Bastion'},
  'pan_cloak':{id:'emblem_vanguard', name:'shieldtank Emblem', icon:'🧥', imgId: 96, grantedTrait: 'Vanguard'},
  'pan_belt':{id:'emblem_brawler', name:'hptank Emblem', icon:'💖', imgId: 97, grantedTrait: 'Brawler'},
  'pan_glove':{id:'emblem_rogue', name:'assassintrait Emblem', icon:'🥊', imgId: 98, grantedTrait: 'Rogue'},
  'unbuildable_anima': {id:'emblem_anima', name:'animasquad Emblem', icon:'🛡️', imgId: 101, grantedTrait: 'Anima'},
  'unbuildable_psionic': {id:'emblem_psionic', name:'Psyops Emblem', icon:'🔮', imgId: 102, grantedTrait: 'Psionic'},
  'unbuildable_sniper': {id:'emblem_sniper', name:'rangedtrait Emblem', icon:'🏹', imgId: 103, grantedTrait: 'Sniper'}
};

/* ── 消費アイテム ── */
const CONSUMABLES = {
  TINY_DUPE: { id: 'tiny_dupe', name: 'Tiny Champion Duplicator', icon: '🔹', type:'consumable', imgId: 905 },
  LESSER_DUPE: { id: 'lesser_dupe', name: 'Lesser Champion Duplicator', icon: '🔹', type:'consumable', imgId: 901 },
  CHAMP_DUPE: { id: 'champ_dupe', name: 'Champion Duplicator', icon: '🔸', type:'consumable', imgId: 902 },
  REFORGER: { id: 'reforger', name: 'Reforger', icon: '🔨', type:'consumable', imgId: 903 },
  REMOVER: { id: 'remover', name: 'itemremover', icon: '🧲', type:'consumable', imgId: 904 }

};

/* ── アーティファクト ── */
const ARTIFACTS = [
  { id: 'ahris_aura', name: "Ahri's Aura", jaName: 'アーリのオーラ', type: 'artifact', imgName: 'tft17_item_artifact_ahriartifact' },
  { id: 'evelynns_intuition', name: "Evelynn's Intuition", jaName: 'イブリンの直感', type: 'artifact', imgName: 'tft17_item_artifact_evelynnartifact' },
  { id: 'trinityforce', name: 'Trinity Force', jaName: 'インフィニティ フォース', type: 'artifact', imgName: 'tft4_item_ornninfinityforce' },
  { id: 'varuss_tenacity', name: "Varus's Tenacity", jaName: 'ヴァルスの執念', type: 'artifact', imgName: 'tft17_item_artifact_varusartifact' },
  { id: 'witsend', name: "Wit's End", jaName: 'ウィッツ エンド', type: 'artifact', imgName: 'tft_item_artifact_witsend' },
  { id: 'voidgauntlet', name: 'Void Gauntlet', jaName: 'ヴォイド ガントレット', type: 'artifact', imgName: 'tft_item_artifact_voidgauntlet' },
  { id: 'ekkos_patience', name: "Ekko's Patience", jaName: 'エコーの忍耐', type: 'artifact', imgName: 'tft17_item_artifact_ekkoartifact' },
  { id: 'gamblersblade', name: "Gambler's Blade", jaName: 'ギャンブラーの剣', type: 'artifact', imgName: 'tft7_item_shimmerscalegamblersblade' },
  { id: 'goldcollector', name: 'The Collector', jaName: 'ゴールド コレクター', type: 'artifact', imgName: 'tft4_item_ornnthecollector' },
  { id: 'seekersarmguard', name: "Seeker's Armguard", jaName: 'シーカー アームガード', type: 'artifact', imgName: 'tft_item_artifact_seekersarmguard' },
  { id: 'silvermeredawn', name: 'Silvermere Dawn', jaName: 'シルバーミアの夜明け', type: 'artifact', imgName: 'tft_item_artifact_silvermeredawn' },
  { id: 'statikkshiv_artifact', name: 'Statikk Shiv Artifact', jaName: 'スタティック シヴ', type: 'artifact', imgName: 'tft_item_artifact_statikkshiv' },
  { id: 'snipersfocus', name: "Sniper's Focus", jaName: 'スナイパー フォーカス', type: 'artifact', imgName: 'tft9_item_ornnhorizonfocus' },
  { id: 'threshs_lantern', name: "Thresh's Lantern", jaName: 'スレッシュのランタン', type: 'artifact', imgName: 'tft17_item_artifact_threshlantern' },
  { id: 'zhonyasparadox', name: "Zhonya's Paradox", jaName: 'ゾーニャの砂時計', type: 'artifact', imgName: 'tft4_item_ornnzhonyasparadox' },
  { id: 'sorakas_miracle', name: "Soraka's Miracle", jaName: 'ソラカの奇跡', type: 'artifact', imgName: 'tft17_item_artifact_sorakaartifact' },
  { id: 'titanichydra', name: 'Titanic Hydra', jaName: 'タイタン ハイドラ', type: 'artifact', imgName: 'tft_item_artifact_titanichydra' },
  { id: 'deathsdefiance', name: "Death's Defiance", jaName: 'デス ディファイアンス', type: 'artifact', imgName: 'tft4_item_ornndeathsdefiance' },
  { id: 'dawncore', name: 'Dawncore', jaName: 'ドーンコア', type: 'artifact', imgName: 'tft_item_artifact_dawncore' },
  { id: 'hullcrusher', name: 'Hullcrusher', jaName: 'ハルクラッシャー', type: 'artifact', imgName: 'tft9_item_ornnhullbreaker' },
  { id: 'fishbones', name: 'Fishbones', jaName: 'フィッシュボーン', type: 'artifact', imgName: 'tft_item_artifact_fishbones' },
  { id: 'flickerblade', name: 'Flickerblade', jaName: 'フリッカーブレード', type: 'artifact', imgName: 'tft_item_artifact_navoriflickerblades' },
  { id: 'prowlersclaw', name: "Prowler's Claw", jaName: 'プローラー クロウ', type: 'artifact', imgName: 'tft_item_artifact_prowlersclaw' },
  { id: 'mittens', name: 'Mittens', jaName: 'ミトン', type: 'artifact', imgName: 'tft_item_artifact_mittens' },
  { id: 'mogulsmail', name: "Mogul's Mail", jaName: 'モーグル メイル', type: 'artifact', imgName: 'tft7_item_shimmerscalemogulsmail' },
  { id: 'yasuos_bladework', name: "Yasuo's Bladework", jaName: 'ヤスオのブレードワーク', type: 'artifact', imgName: 'tft17_item_artifact_yasuoartifact' },
  { id: 'lightshieldcrest', name: 'Lightshield Crest', jaName: 'ライトシールドのクレスト', type: 'artifact', imgName: 'tft_item_artifact_lightshieldcrest' },
  { id: 'rapidfirecannon_artifact', name: 'Rapid Firecannon Artifact', jaName: 'ラピッド ファイアキャノン', type: 'artifact', imgName: 'tft_item_artifact_rapidfirecannon' },
  { id: 'lichbane', name: 'Lich Bane', jaName: 'リッチ ベイン', type: 'artifact', imgName: 'tft_item_artifact_lichbane' },
  { id: 'ludenstempest', name: "Luden's Tempest", jaName: 'ルーデン テンペスト', type: 'artifact', imgName: 'tft_item_artifact_ludenstempest' },
  { id: 'unendingdespair', name: 'Unending Despair', jaName: '不屈', type: 'artifact', imgName: 'tft_item_artifact_unendingdespair' },
  { id: 'everlastingpact', name: 'Everlasting Pact', jaName: '不滅の協定', type: 'artifact', imgName: 'tft_item_artifact_eternalpact' },
  { id: 'dusksblessing', name: "Dusk's Blessing", jaName: '夕闇の加護', type: 'artifact', imgName: 'tft_item_artifact_aegisofdusk' },
  { id: 'dawnsblessing', name: "Dawn's Blessing", jaName: '夜明けの加護', type: 'artifact', imgName: 'tft_item_artifact_aegisofdawn' },
  { id: 'hatjuice', name: 'Hat Juice', jaName: '帽子ジュース', type: 'artifact', imgName: 'tft_item_artifact_cappajuice' },
  { id: 'blightingjewel', name: 'Blighting Jewel', jaName: '枯死の宝石', type: 'artifact', imgName: 'tft_item_artifact_blightingjewel' },
  { id: 'hellfirehatchet', name: 'Hellfire Hatchet', jaName: '獄炎のハチェット', type: 'artifact', imgName: 'tft_item_artifact_hellfirehatchet' },
  { id: 'talismanofascension', name: 'Talisman of Ascension', jaName: '超越のタリスマン', type: 'artifact', imgName: 'tft_item_artifact_talismanofascension' },
  { id: 'crown_of_demacia', name: 'Crown of Demacia', jaName: 'デマーシアの王冠', type: 'artifact', imgName: 'tft9_item_crownofdemacia' }
];

/* ── レディアントアイテム ── */
const RADIANT_ITEMS = [
  { id: 'r_deathblade', name: 'Luminous Deathblade', jaName: 'レディアント デスブレード', type: 'radiant', imgName: 'tft5_item_deathbladeradiant' },
  { id: 'r_giantslayer', name: 'Demonslayer', jaName: 'レディアント ジャイアントスレイヤー', type: 'radiant', imgName: 'tft5_item_giantslayerradiant' },
  { id: 'r_gunblade', name: 'Hextech Lifeblade', jaName: 'レディアント ヘクステックガンブレード', type: 'radiant', imgName: 'tft5_item_hextechgunbladeradiant' },
  { id: 'r_shojin', name: 'Spear of Hirana', jaName: 'レディアント ショウジンの矛', type: 'radiant', imgName: 'tft5_item_spearofshojinradiant' },
  { id: 'r_edgeofnight', name: 'Brink of Dawn', jaName: 'レディアント ナイトエッジ', type: 'radiant', imgName: 'tft5_item_guardianangelradiant' },
  { id: 'r_bloodthirster', name: 'Blessed Bloodthirster', jaName: 'レディアント ブラッドサースター', type: 'radiant', imgName: 'tft5_item_bloodthirsterradiant' },
  { id: 'r_steraksgage', name: "Sterak's Megashield", jaName: 'レディアント ステラックの篭手', type: 'radiant', imgName: 'tft5_item_steraksgageradiant' },
  { id: 'r_infinityedge', name: 'Zenith Edge', jaName: 'レディアント インフィニティエッジ', type: 'radiant', imgName: 'tft5_item_infinityedgeradiant' },
  { id: 'r_rapidfirecannon', name: 'Crest of Cinders', jaName: 'レディアント レッドバフ', type: 'radiant', imgName: 'tft5_item_rapidfirecannonradiant' }, 
  { id: 'r_guinsoo', name: "Guinsoo's Reckoning", jaName: 'レディアント グインソー レイジブレード', type: 'radiant', imgName: 'tft5_item_guinsoosragebladeradiant' },
  { id: 'r_statikk', name: "Statikk's Favor", jaName: 'レディアント ヴォイドスタッフ', type: 'radiant', imgName: 'tft5_item_statikkshivradiant' },
  { id: 'r_titans', name: "Titan's Vow", jaName: 'レディアント 巨人の誓い', type: 'radiant', imgName: 'tft5_item_titansresolveradiant' },
  { id: 'r_runaan', name: "Runaan's Tempest", jaName: 'レディアント クラーケンの怒り', type: 'radiant', imgName: 'tft5_item_runaanshurricaneradiant' },
  { id: 'r_nashor', name: "Baron's Gift", jaName: 'レディアント ナッシャー トゥース', type: 'radiant', imgName: 'tft5_item_leviathanradiant' },
  { id: 'r_lastwhisper', name: 'Eternal Whisper', jaName: 'レディアント ラストウィスパー', type: 'radiant', imgName: 'tft5_item_lastwhisperradiant' },
  { id: 'r_rabadon', name: "Rabadon's Ascended Deathcap", jaName: 'レディアント ラバドンデスキャップ', type: 'radiant', imgName: 'tft5_item_rabadonsdeathcapradiant' },
  { id: 'r_archangel', name: "Urf-Angel's Staff", jaName: 'レディアント アークエンジェルスタッフ', type: 'radiant', imgName: 'tft5_item_archangelsstaffradiant' },
  { id: 'r_crownguard', name: 'Royal Crownshield', jaName: 'レディアント クラウンガード', type: 'radiant', imgName: 'tft5_item_crownguardradiant' },
  { id: 'r_ionic', name: 'Covalent Spark', jaName: 'レディアント アイオニックスパーク', type: 'radiant', imgName: 'tft5_item_ionicsparkradiant' },
  { id: 'r_morello', name: 'More More-ellonomicon', jaName: 'レディアント モレロノミコン', type: 'radiant', imgName: 'tft5_item_morellonomiconradiant' },
  { id: 'r_jeweled', name: 'Glamorous Gauntlet', jaName: 'レディアント ジュエル ガントレット', type: 'radiant', imgName: 'tft5_item_jeweledgauntletradiant' },
  { id: 'r_bluebuff', name: 'Blue Blessing', jaName: 'レディアント ブルーバフ', type: 'radiant', imgName: 'tft5_item_bluebuffradiant' },
  { id: 'r_vow', name: "Bulwark's Oath", jaName: 'レディアント プロテクターの誓い', type: 'radiant', imgName: 'tft5_item_frozenheartradiant' },
  { id: 'r_adaptive', name: 'Jaksho the Protean', jaName: 'レディアント アダプティブヘルム', type: 'radiant', imgName: 'tft5_item_adaptivehelmradiant' },
  { id: 'r_redemption', name: 'Absolution', jaName: 'レディアント スピリット ビサージュ', type: 'radiant', imgName: 'tft5_item_redemptionradiant' },
  { id: 'r_hoj', name: 'Fist of Fairness', jaName: 'レディアント ハンド オブ ジャスティス', type: 'radiant', imgName: 'tft5_item_handofjusticeradiant' },
  { id: 'r_bramble', name: 'Rosethorn Vest', jaName: 'レディアント ブランブルベスト', type: 'radiant', imgName: 'tft5_item_bramblevestradiant' },
  { id: 'r_gargoyle', name: 'Dvarapala Stoneplate', jaName: 'レディアント ガーゴイルストーンプレート', type: 'radiant', imgName: 'tft5_item_gargoylestoneplateradiant' },
  { id: 'r_sunfire', name: 'Sunlight Cape', jaName: 'レディアント サンファイアケープ', type: 'radiant', imgName: 'tft5_item_sunfirecaperadiant' },
  { id: 'r_steadfast', name: 'Legacy of the Colossus', jaName: 'レディアント 揺るがぬ心', type: 'radiant', imgName: 'tft5_item_nightharvesterradiant' },
  { id: 'r_dragon', name: "Dragon's Will", jaName: 'レディアント ドラゴン クロウ', type: 'radiant', imgName: 'tft5_item_dragonsclawradiant' },
  { id: 'r_evenshroud', name: 'Equinox', jaName: 'レディアント イーブンシュラウド', type: 'radiant', imgName: 'tft5_item_spectralgauntletradiant' },
  { id: 'r_quicksilver', name: 'Quickestsilver', jaName: 'レディアント クイックシルバー', type: 'radiant', imgName: 'tft5_item_quicksilverradiant' },
  { id: 'r_warmog', name: "Warmog's Pride", jaName: 'レディアント ワーモグ アーマー', type: 'radiant', imgName: 'tft5_item_warmogsarmorradiant' },
  { id: 'r_guardbreaker', name: 'Willbreaker', jaName: 'レディアント ストライカー フレイル', type: 'radiant', imgName: 'tft5_item_trapclawradiant' },
  { id: 'r_thiefs', name: "Rascal's Gloves", jaName: 'レディアント 盗賊のグローブ', type: 'radiant', imgName: 'tft5_item_thiefsglovesradiant' }
];
